from typing import Dict

# Все тексты для локализации
TEXTS: Dict[str, Dict[str, str]] = {
    "ru": {
        "language_select": "Выберите язык / Choose language / Tilni tanlang / Забони интихоб кунед",
        "welcome": "Добро пожаловать в VPN-сервис!",
        "profile": "Мой профиль",
        "buy_vpn": "Купить VPN",
        "about": "О сервисе",
        "support": "Поддержка",
        "back": "Назад",
        "subscription_active": "✅ Активна",
        "subscription_expires": "Действует до: {date}",
        "vpn_key": "VPN-ключ: {vpn_key}",
        "no_subscription": "Активных подписок нет",
        "select_tariff": "Выберите тариф:",
        "months": "{months} месяц",
        "months_3_6": "{months} месяца",
        "months_12": "{months} месяцев",
        "select_payment": "Выберите удобный способ оплаты",
        "payment_test": "Тест (не работает)",
        "payment_sbp": "СБП (работает)",
        "sbp_payment_text": "Оплата через СБП.\nПереведите средства по реквизитам ниже.\nПосле оплаты нажмите кнопку «Я оплатил».",
        "paid_button": "Я оплатил",
        "payment_pending": "📨 Ожидайте, подтверждаем.\n⏳ Подтверждение займёт до 5 минут.",
        "payment_approved": "✅ Оплата подтверждена!\nВаш VPN-ключ: {vpn_key}\nПодписка активна до: {date}",
        "payment_rejected": "❌ Оплата не подтверждена.\nЕсли вы уверены, что оплатили — обратитесь в поддержку.",
        "about_text": "Наш сервис предоставляет стабильный и безопасный VPN.",
        "privacy_policy": "Политика конфиденциальности",
        "support_text": "Поддержка\nEmail: {email}\nTelegram: {telegram}",
        "change_language": "Изменить язык",
        "admin_payment_notification": "💰 Новая оплата\nПользователь: @{username}\nTelegram ID: {telegram_id}\nТариф: {tariff} месяцев\nСтоимость: {price} руб.",
        "admin_approve": "Подтвердить",
        "admin_reject": "Отклонить",
        "privacy_policy_text": "Политика конфиденциальности\n\nМы храним только необходимые данные для предоставления услуг VPN.",
    },
    "en": {
        "language_select": "Select language / Выберите язык / Tilni tanlang / Забони интихоб кунед",
        "welcome": "Welcome to VPN service!",
        "profile": "My Profile",
        "buy_vpn": "Buy VPN",
        "about": "About",
        "support": "Support",
        "back": "Back",
        "subscription_active": "✅ Active",
        "subscription_expires": "Valid until: {date}",
        "vpn_key": "VPN key: {vpn_key}",
        "no_subscription": "No active subscriptions",
        "select_tariff": "Select tariff:",
        "months": "{months} month",
        "months_3_6": "{months} months",
        "months_12": "{months} months",
        "select_payment": "Choose a convenient payment method",
        "payment_test": "Test (not working)",
        "payment_sbp": "SBP (working)",
        "sbp_payment_text": "Payment via SBP.\nTransfer funds to the details below.\nAfter payment, click the «I paid» button.",
        "paid_button": "I paid",
        "payment_pending": "📨 Please wait, we are confirming.\n⏳ Confirmation will take up to 5 minutes.",
        "payment_approved": "✅ Payment confirmed!\nYour VPN key: {vpn_key}\nSubscription active until: {date}",
        "payment_rejected": "❌ Payment not confirmed.\nIf you are sure you paid, please contact support.",
        "about_text": "Our service provides stable and secure VPN.",
        "privacy_policy": "Privacy Policy",
        "support_text": "Support\nEmail: {email}\nTelegram: {telegram}",
        "change_language": "Change language",
        "admin_payment_notification": "💰 New payment\nUser: @{username}\nTelegram ID: {telegram_id}\nTariff: {tariff} months\nPrice: {price} rub.",
        "admin_approve": "Approve",
        "admin_reject": "Reject",
        "privacy_policy_text": "Privacy Policy\n\nWe store only the necessary data to provide VPN services.",
    },
    "uz": {
        "language_select": "Tilni tanlang / Выберите язык / Choose language / Забони интихоб кунед",
        "welcome": "VPN xizmatiga xush kelibsiz!",
        "profile": "Mening profilim",
        "buy_vpn": "VPN sotib olish",
        "about": "Xizmat haqida",
        "support": "Qo'llab-quvvatlash",
        "back": "Orqaga",
        "subscription_active": "✅ Faol",
        "subscription_expires": "Amal qiladi: {date}",
        "vpn_key": "VPN kalit: {vpn_key}",
        "no_subscription": "Faol obunalar yo'q",
        "select_tariff": "Tarifni tanlang:",
        "months": "{months} oy",
        "months_3_6": "{months} oy",
        "months_12": "{months} oy",
        "select_payment": "Qulay to'lov usulini tanlang",
        "payment_test": "Test (ishlamaydi)",
        "payment_sbp": "SBP (ishlaydi)",
        "sbp_payment_text": "SBP orqali to'lov.\nQuyidagi ma'lumotlar bo'yicha pul o'tkazing.\nTo'lovdan keyin «Men to'ladim» tugmasini bosing.",
        "paid_button": "Men to'ladim",
        "payment_pending": "📨 Kutib turing, tasdiqlaymiz.\n⏳ Tasdiqlash 5 minutgacha davom etadi.",
        "payment_approved": "✅ To'lov tasdiqlandi!\nSizning VPN kalitingiz: {vpn_key}\nObuna faol: {date}",
        "payment_rejected": "❌ To'lov tasdiqlanmadi.\nAgar to'laganingizga ishonchingiz komil bo'lsa — qo'llab-quvvatlashga murojaat qiling.",
        "about_text": "Bizning xizmat barqaror va xavfsiz VPN taqdim etadi.",
        "privacy_policy": "Maxfiylik siyosati",
        "support_text": "Qo'llab-quvvatlash\nEmail: {email}\nTelegram: {telegram}",
        "change_language": "Tilni o'zgartirish",
        "admin_payment_notification": "💰 Yangi to'lov\nFoydalanuvchi: @{username}\nTelegram ID: {telegram_id}\nTarif: {tariff} oy\nNarx: {price} so'm",
        "admin_approve": "Tasdiqlash",
        "admin_reject": "Rad etish",
        "privacy_policy_text": "Maxfiylik siyosati\n\nBiz VPN xizmatlarini taqdim etish uchun faqat zarur ma'lumotlarni saqlaymiz.",
    },
    "tj": {
        "language_select": "Забони интихоб кунед / Выберите язык / Choose language / Tilni tanlang",
        "welcome": "Хуш омадед ба хизмати VPN!",
        "profile": "Профили ман",
        "buy_vpn": "Хариди VPN",
        "about": "Дар бораи хизмат",
        "support": "Дастгирӣ",
        "back": "Бозгашт",
        "subscription_active": "✅ Фаъол",
        "subscription_expires": "То: {date} эътибор дорад",
        "vpn_key": "Калиди VPN: {vpn_key}",
        "no_subscription": "Обунаҳои фаъол нест",
        "select_tariff": "Тарифро интихоб кунед:",
        "months": "{months} моҳ",
        "months_3_6": "{months} моҳ",
        "months_12": "{months} моҳ",
        "select_payment": "Усули қулайи пардохтро интихоб кунед",
        "payment_test": "Тест (коре намекунад)",
        "payment_sbp": "СБП (коре мекунад)",
        "sbp_payment_text": "Пардохт тавассути СБП.\nМаблағҳоро ба реквизитҳои зерӣ гузаронед.\nПас аз пардохт, тугмаи «Ман пардохт кардам»-ро пахш кунед.",
        "paid_button": "Ман пардохт кардам",
        "payment_pending": "📨 Интизор шавед, тасдиқ мекунем.\n⏳ Тасдиқ то 5 дақиқа давом мекунад.",
        "payment_approved": "✅ Пардохт тасдиқ шуд!\nКалиди VPN-и шумо: {vpn_key}\nОбуна то: {date} фаъол аст",
        "payment_rejected": "❌ Пардохт тасдиқ нашуд.\nАгар мӯътақид ҳастед, ки пардохт кардед — ба дастгирӣ муроҷиат кунед.",
        "about_text": "Хизмати моро VPN-и устувор ва бехатар таъмин мекунад.",
        "privacy_policy": "Сиёсати махфият",
        "support_text": "Дастгирӣ\nEmail: {email}\nTelegram: {telegram}",
        "change_language": "Тағйири забон",
        "admin_payment_notification": "💰 Пардохти нав\nКорбар: @{username}\nTelegram ID: {telegram_id}\nТариф: {tariff} моҳ\nНарх: {price} сом.",
        "admin_approve": "Тасдиқ кардан",
        "admin_reject": "Рад кардан",
        "privacy_policy_text": "Сиёсати махфият\n\nМо танҳо маълумоти зарурӣ барои таъмини хидматҳои VPN нигоҳ медорем.",
    },
}


def get_text(language: str, key: str, **kwargs) -> str:
    """Получить переведенный текст"""
    lang = language if language in TEXTS else "ru"
    text = TEXTS[lang].get(key, TEXTS["ru"].get(key, key))
    return text.format(**kwargs) if kwargs else text


# Кнопки для выбора языка
LANGUAGE_BUTTONS = {
    "ru": "Русский",
    "en": "English",
    "uz": "O'zbek",
    "tj": "Тоҷикӣ",
}

