#!/usr/bin/env python3
"""
Coverage ratchet gate.

Reads:
- ``.coverage-baseline`` — required minimum percentage (float).
- ``coverage.xml`` — produced by ``pytest --cov --cov-report=xml``.

Fails (exit 1) if measured coverage < baseline. Always prints both numbers
so CI logs are self-explanatory.

Coverage targets are reviewed quarterly (see docs/marketing/PLAYBOOK.md and
the engineering quality plan). The ratchet should advance, never regress.

Optional: pass ``--bump`` to rewrite the baseline to ``floor(measured)`` —
useful when the team intentionally locks in newly-added tests.
"""
from __future__ import annotations

import math
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_FILE = REPO_ROOT / ".coverage-baseline"
COVERAGE_XML = REPO_ROOT / "coverage.xml"


def read_baseline() -> float:
    if not BASELINE_FILE.exists():
        print("WARN: .coverage-baseline missing, treating baseline as 0.0", file=sys.stderr)
        return 0.0
    text = BASELINE_FILE.read_text().strip()
    if not text:
        return 0.0
    try:
        return float(text)
    except ValueError:
        print(f"ERROR: .coverage-baseline contains non-numeric value: {text!r}", file=sys.stderr)
        sys.exit(2)


def read_measured() -> float:
    if not COVERAGE_XML.exists():
        print(f"ERROR: {COVERAGE_XML} missing — did you run pytest --cov --cov-report=xml?", file=sys.stderr)
        sys.exit(2)
    # coverage.xml is generated by pytest-cov in the same job — trusted source.
    tree = ET.parse(COVERAGE_XML)  # noqa: S314 — local artifact, not user input
    line_rate = tree.getroot().attrib.get("line-rate")
    if line_rate is None:
        print("ERROR: coverage.xml missing line-rate attribute", file=sys.stderr)
        sys.exit(2)
    return float(line_rate) * 100.0


def main() -> int:
    bump = "--bump" in sys.argv
    baseline = read_baseline()
    measured = read_measured()
    print(f"COVERAGE_BASELINE = {baseline:.2f}%")
    print(f"COVERAGE_MEASURED = {measured:.2f}%")

    if bump:
        new_baseline = math.floor(measured)
        BASELINE_FILE.write_text(f"{new_baseline:.1f}\n")
        print(f"BASELINE_BUMPED to {new_baseline:.1f}%")
        return 0

    if measured + 1e-6 < baseline:
        print(f"FAIL: coverage dropped below baseline ({measured:.2f}% < {baseline:.2f}%)")
        return 1
    print("OK: coverage is at or above baseline")
    return 0


if __name__ == "__main__":
    sys.exit(main())
